---
# tasks file for ansible-role-cutadapt

- name: Detect environment
  set_fact:
    base_path: "{% if ansible_domain == 'cedar.computecanada.ca' %} \ 
                {{ ansible_env.HOME }}/scratch{% else %}{{ ansible_env.HOME }}{% endif %}"
  when: base_path is not defined

- name: Create /tmp directory
  file:
    path: /tmp/biol
    state: directory
  notify: Remove biol tmp dir

- name: Set conda executable variable
  set_fact:
    conda_executable: "{{ base_path }}/.biolighthouse/software/conda/bin/conda"
  when: conda_executable is not defined

- name: Create a conda environment
  conda_create:
    name: "bl_cutadapt"
    executable: "{{ base_path }}/.biolighthouse/software/conda/bin/conda"

- name: Put environment activation in .bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "conda activate bl_cutadapt"
  notify: Remove environment activation in .bashrc

- name: Install biopython via conda
  conda_install:
    name: 'biopython'
    version: '1.71'
    executable: "{{ conda_executable }}"
    channel: bioconda
    environment: bl_cutadapt

- name: Install cutadapt via conda
  conda_install:
    name: 'cutadapt'
    version: '1.17'
    executable: "{{ conda_executable }}"
    channel: [bioconda, conda-forge]
    environment: bl_cutadapt
